version: 2.1
jobs:
  build:
    docker:
      - image: fr3akyphantom/droid-builder:latest
    environment:
      MANIFEST_BRANCH: 'android-9.0'
      VERSION: '3.0.0'
      MAINTAINER: '@ElytrA8'
      VENDOR: 'xiaomi'
      CODENAME: 'rosy'
      FLAVOR: 'eng'
      #TEST_BUILD: 'true'
      PB_OFFICIAL: 'true'
      CHANGELOG: |
        - Initial Official Build
      EXTRA_CMD: "cd vendor/qcom/opensource/commonsys && rm -rf cryptfs_hw Android.bp && wget -q https://raw.githubusercontent.com/ElytrA8/cryptfs_fixup/main/Android.bp && cd ../../../.."
    working_directory: /home/builder/pitchblack
    steps:
      - run:
          name: AIO Build
          command: |
            wget -q https://raw.githubusercontent.com/PitchBlackRecoveryProject/vendor_utils/pb/build.sh
            source build.sh
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: 'android-9.0'
          context: org-global
